## Lecture04 Octave Tutorial

### Basic Operations

**numerical calculation**:

``` Octave
octave:1> 5+6
ans =  11
octave:2> 3-2
ans =  1
octave:3> 5*8
ans =  40
octave:4> 1/2
ans =  0.50000
octave:5> 2^6
ans =  64
```

**logical operation**:
``` Octave
octave:1> 1 == 2
ans = 0
octave:2> 1 ~= 2
ans =  1
octave:3> 1 && 0    % AND
ans = 0
octave:4> 1 || 0    % OR
ans =  1
octave:5> xor(1,0) % XOR
ans =  1
```

**assignment and output**:
``` Octave
octave:1> a = 3
a =  3
octave:2> a = 3; % simicolon supressing output
octave:3> a
a =  3
octave:4> b = 'hello';
octave:5> a = pi;
octave:6> disp(a);
 3.1416
octave:7> disp(sprintf('2 decimal :%0.2f', a));
2 decimal :3.14
octave:8> format long
octave:9> disp(a);
 3.14159265358979
octave:10> format short
octave:11> disp(a);
 3.1416
```


**matrix operation**:
``` Octave
octave:1> A = [1 2; 3 4; 5 6]
A =

   1   2
   3   4
   5   6

octave:2> v = [1 2 3]
v =

   1   2   3

octave:3> v = [1; 2; 3]
v =

   1
   2
   3

octave:4> v = 1:0.1:2
v =

    1.0000    1.1000    1.2000    1.3000    1.4000    1.5000    1.6000    1.7000    1.8000    1.9000    2.0000

octave:5> v = 1:10
v =

    1    2    3    4    5    6    7    8    9   10
octave:6> ones(2, 3)
ans =

   1   1   1
   1   1   1

octave:7> zeros(2, 3)
ans =

   0   0   0
   0   0   0

octave:8> rand(2, 3)
ans =

   0.69003   0.85555   0.99635
   0.24037   0.47993   0.39745

octave:9> randn(2, 3)
ans =

  -2.25914   0.59106   1.05277
   0.40133  -1.46558   1.40913

octave:10> eye(3)

ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1
   
octave:11> size(A)
ans =

   3   2

octave:12> size(A, 1)
ans =  3
octave:13> size(A, 2)
ans =  2
octave:14> A(3, 2)
ans =  6
octave:15> A(3,:)
ans =

   5   6

octave:16> A(:,2)
ans =

   2
   4
   6

octave:17> A([1 3],:)
ans =

   1   2
   5   6
   
octave:18> A(:,2) = [10;12;14]
A =

    1   10
    3   12
    5   14

octave:19> A = [A, [100; 101; 102]]
A =

     1    10   100
     3    12   101
     5    14   102

octave:20> A(:) % put all elements of A into a single vector
ans =

     1
     3
     5
    10
    12
    14
   100
   101
   102
octave:21> B = [A A]
B =

     1    10   100     1    10   100
     3    12   101     3    12   101
     5    14   102     5    14   102

octave:22> C = [A; A]
C =

     1    10   100
     3    12   101
     5    14   102
     1    10   100
     3    12   101
     5    14   102
```

**other**: pwd, ls, cd, who, whos, clear, clc; 
```
octave:1> PS1('>> ');
>> help <command>;
```

## Moving Data


``` Octave
octave:1> load featuresX.dat
octave:2> v = 1:10
v =

    1    2    3    4    5    6    7    8    9   10

octave:3> save hello.mat v
octave:4> save hello.txt v -ascii % save as text (ASCII)
```

## Computing on Data

**matrix function**: max, find, sum, pinv.

``` Octave
octave:1> A = [1 2; 3 4; 5 6];
octave:2> B = [11 12; 13 14; 15 16];
octave:3> C = [1 1; 2 2];
octave:4> A.*B
ans =

   11   24
   39   56
   75   96

octave:5> A*C
ans =

    5    5
   11   11
   17   17

octave:6> A.^ 2
ans =

    1    4
    9   16
   25   36

octave:7> 1 ./ A
ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667

octave:8> A + 1
ans =

   2   3
   4   5
   6   7

octave:9> A'
ans =

   1   3   5
   2   4   6

octave:10> A < 3
ans =

   1   1
   0   0
   0   0

octave:11> max(A, [], 1) % maximum element in each column
ans =

   5   6

octave:12> max(A, [], 2) % maximum element in each row
ans =

   2
   4
   6
```



## Plotting Data

**plot commands**: hist, plot, hold on (plot in a new figure), xlable, ylable, lengend, title, print -dpng 'filename', close, figure(no), subplot (divides plot), axis, clf, imagesc.

``` Octave
>> imagesc(A), colorbar, colormap gray;
```

## Control statement

**control statement**: for, while, if...else, break.
**function statement**: 

``` Octave
function y = myfunc(x)                                                                                                            
    y = x^2;

function [y1, y2] = myfunc2(x)
    y1 = x;
    y2 = x^2;
```